<#
.Function:
    convert sql key words to uppercase

.Example：
    PS > file.ps1 -path "C:\test_sql"
    PS > file.ps1 "C:\test_sql"
    PS > file.ps1 C:\test_sql
#>

param(
    [string] $sql_file_path
)


$sql_key_words = 'ABSOLUTE', 'ACTION', 'ADA', 'ADD', 'ADMIN', 'ADDRESS', 'AFTER',
    'AGGREGATE', 'ALIAS', 'ALL', 'ALLOCATE', 'ALTER', 'AND', 'ANY', 'ARE',
    'ARRAY', 'AS', 'ASC', 'ASENSITIVE', 'ASSERTION', 'ASYMMETRIC', 'AT',
    'ATOMIC', 'AUTHORIZATION', 'AVG', 'BEFORE', 'BEGIN', 'BETWEEN', 'BINARY',
    'BIT', 'BIT_LENGTH', 'BLOB', 'BOOLEAN', 'BOTH', 'BREADTH', 'BY', 'CALL',
    'CALLED', 'CARDINALITY', 'CASCADE', 'CASCADED', 'CASE', 'CAST', 'CATALOG',
    'CHAR', 'CHAR_LENGTH', 'CHARACTER', 'CHARACTER_LENGTH', 'CHECK', 'CLASS',
    'CLOB', 'CLOSE', 'COALESCE', 'COLLATE', 'COLLATION', 'COLLECT', 'COLUMN',
    'COMMIT', 'COMPLETION', 'CONDITION', 'CONNECT', 'CONNECTION', 'CONSTRAINT',
    'CONSTRAINTS', 'CONSTRUCTOR', 'CONTINUE', 'CONVERT', 'CORR',
    'CORRESPONDING', 'COUNT', 'COVAR_POP', 'COVAR_SAMP', 'CREATE', 'CROSS',
    'CUBE', 'CUME_DIST', 'CURRENT', 'CURRENT_CATALOG', 'CURRENT_DATE',
    'CURRENT_DEFAULT_TRANSFORM_GROUP', 'CURRENT_PATH', 'CURRENT_ROLE',
    'CURRENT_SCHEMA', 'CURRENT_TIME', 'CURRENT_TIMESTAMP',
    'CURRENT_TRANSFORM_GROUP_FOR_TYPE', 'CURRENT_USER', 'CURSOR', 'CYCLE',
    'DATA', 'DATE', 'DAY', 'DEALLOCATE', 'DEC', 'DECIMAL', 'DECLARE', 'DEFAULT',
    'DEFERRABLE', 'DEFERRED', 'DELETE', 'DEPTH', 'DEREF', 'DESC', 'DESCRIBE',
    'DESCRIPTOR', 'DESTROY', 'DESTRUCTOR', 'DETERMINISTIC', 'DIAGNOSTICS',
    'DICTIONARY', 'DISCONNECT', 'DISTINCT', 'DOMAIN', 'DOUBLE', 'DROP',
    'DYNAMIC', 'EACH', 'ELEMENT', 'ELSE', 'END', 'END-EXEC', 'EQUALS', 'ESCAPE',
    'EVERY', 'EXCEPT', 'EXCEPTION', 'EXEC', 'EXECUTE', 'EXISTS', 'EXTERNAL',
    'EXTRACT', 'FALSE', 'FETCH', 'FILTER', 'FIRST', 'FLOAT', 'FOR', 'FOREIGN',
    'FORTRAN', 'FOUND', 'FREE', 'FROM', 'FULL', 'FULLTEXTTABLE', 'FUSION',
    'GENERAL', 'GET', 'GLOBAL', 'GO', 'GOTO', 'GRANT', 'GROUP', 'GROUPING',
    'HAVING', 'HOLD', 'HOST', 'HOUR', 'IDENTITY', 'IGNORE', 'IMMEDIATE', 'IN',
    'INCLUDE', 'INDEX', 'INDICATOR', 'INITIALIZE', 'INITIALLY', 'INNER',
    'INOUT', 'INPUT', 'INSENSITIVE', 'INSERT', 'INT', 'INTEGER', 'INTERSECT',
    'INTERSECTION', 'INTERVAL', 'INTO', 'IS', 'ISOLATION', 'ITERATE', 'JOIN',
    'KEY', 'LANGUAGE', 'LARGE', 'LAST', 'LATERAL', 'LEADING', 'LEFT', 'LESS',
    'LEVEL', 'LIKE', 'LIKE_REGEX', 'LIMIT', 'LN', 'LOCAL', 'LOCALTIME',
    'LOCALTIMESTAMP', 'LOCATOR', 'LOWER', 'MAP', 'MATCH', 'MAX', 'MEMBER',
    'METHOD', 'MIN', 'MINUTE', 'MOD', 'MODIFIES', 'MODIFY', 'MODULE', 'MONTH',
    'MULTISET', 'NAME', 'NAMES', 'NATIONAL', 'NATURAL', 'NCHAR', 'NCLOB', 'NEW',
    'NEXT', 'NO', 'NONE', 'NORMALIZE', 'NOT', 'NULL', 'NULLIF', 'NUMERIC',
    'OBJECT', 'OCCURRENCES_REGEX', 'OCTET_LENGTH', 'OF', 'OLD', 'ON', 'ONLY',
    'OPEN', 'OPERATION', 'OPTION', 'OR', 'ORDER', 'ORDINALITY', 'OUT', 'OUTER',
    'OUTPUT', 'OVERLAPS', 'OVERLAY', 'PAD', 'PARAMETER', 'PARAMETERS',
    'PARTIAL', 'PARTITION', 'PASCAL', 'PATH', 'PERCENT_RANK', 'WHILE',
    'PERCENTILE_CONT', 'PERCENTILE_DISC', 'POSITION', 'POSITION_REGEX',
    'POSTFIX', 'PRECISION', 'PREFIX', 'PREORDER', 'PREPARE', 'PRESERVE',
    'PRIMARY', 'PRIOR', 'PRIVILEGES', 'PROCEDURE', 'PUBLIC', 'RANGE', 'READ',
    'READS', 'REAL', 'RECURSIVE', 'REF', 'REFERENCES', 'REFERENCING',
    'REGR_AVGX', 'REGR_AVGY', 'REGR_COUNT', 'REGR_INTERCEPT', 'REGR_R2',
    'REGR_SLOPE', 'REGR_SXX', 'REGR_SXY', 'REGR_SYY', 'RELATIVE', 'RELEASE',
    'RESTRICT', 'RESULT', 'RETURNS', 'REVOKE', 'RIGHT', 'ROLE', 'ROLLBACK',
    'ROLLUP', 'ROUTINE', 'ROW', 'ROWS', 'SAVEPOINT', 'SCHEMA', 'SCOPE',
    'SCROLL', 'SEARCH', 'SECOND', 'SECTION', 'SELECT', 'SENSITIVE', 'SEQUENCE',
    'SESSION', 'SESSION_USER', 'SET', 'SETS', 'SIMILAR', 'SIZE', 'SMALLINT',
    'SOME', 'SPACE', 'SPECIFIC', 'SPECIFICTYPE', 'SQL', 'SQLCA', 'SQLCODE',
    'SQLERROR', 'SQLEXCEPTION', 'SQLSTATE', 'SQLWARNING', 'START', 'STATE',
    'STATEMENT', 'STATIC', 'STDDEV_POP', 'STDDEV_SAMP', 'STRUCTURE',
    'SUBMULTISET', 'SUBSTRING', 'SUBSTRING_REGEX', 'SUM', 'SYMMETRIC', 'SYSTEM',
    'SYSTEM_USER', 'TABLE', 'TEMPORARY', 'TERMINATE', 'THAN', 'THEN', 'TIME',
    'TIMESTAMP', 'TIMEZONE_HOUR', 'TIMEZONE_MINUTE', 'TO', 'TRAILING',
    'TRANSACTION', 'TRANSLATE', 'TRANSLATE_REGEX', 'TRANSLATION', 'TREAT',
    'TRIM', 'TRUE', 'UESCAPE', 'UNDER', 'UNION', 'UNIQUE', 'UNKNOWN', 'UNNEST',
    'UPDATE', 'UPPER', 'USAGE', 'USER', 'USING', 'VALUE', 'VALUES', 'VAR_POP',
    'VAR_SAMP', 'VARCHAR', 'VARIABLE', 'VARYING', 'WHEN', 'WHENEVER', 'WHERE',
    'WIDTH_BUCKET', 'VIEW', 'WINDOW', 'WITH', 'WITHIN', 'WITHOUT', 'WORK',
    'WRITE', 'XMLAGG', 'XMLATTRIBUTES', 'XMLBINARY', 'XMLCAST', 'XMLCOMMENT',
    'XMLCONCAT', 'XMLDOCUMENT', 'XMLELEMENT', 'XMLEXISTS', 'XMLFOREST',
    'XMLITERATE', 'XMLNAMESPACES', 'XMLPARSE', 'XMLPI', 'XMLQUERY',
    'XMLSERIALIZE', 'XMLTABLE', 'XMLTEXT', 'XMLVALIDATE', 'YEAR', 'ZONE',
    'TRY', 'CATCH', 'THROW', 'FUNCTION', 'TRIGGER', 'USE', 'CLUSTERED', 'NONCLUSTERED'
    'MERGE'

$content = Get-Content $sql_file_path

foreach($_ in $sql_key_words)
{
    $content = $content -replace "\b$_\b", $_
}

Set-Content $sql_file_path $content